// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func contact() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"section-dark\" id=\"contact\"><!--begin container--><div class=\"container\"><!--begin row--><div class=\"row margin-bottom-50\"><!--begin col-md-10--><div class=\"col-md-10 col-md-offset-1 text-center\"><h2 class=\"section-title grey\">Me contacter</h2><div class=\"separator_wrapper_white\"><i class=\"icon icon-star-two grey\"></i></div></div><!--end col-md-10--></div><!--end row--><!--begin row--><div class=\"row\"><!--begin success message --><p class=\"contact_success_box\" style=\"display:none;\">We received your message and you'll hear from us soon. Thank You!</p><!--end success message --><!--begin contact form --><form id=\"contact-form\" class=\"contact\" action=\"\" method=\"post\"><!--begin col-md-6--><div class=\"col-md-6\"><input class=\"contact-input white-input\" required=\"\" name=\"contact_names\" placeholder=\"Nom*\" type=\"text\"> <input class=\"contact-input white-input\" required=\"\" name=\"contact_subject\" placeholder=\"Sujet*\" type=\"text\"></div><!--end col-md-6--><!--begin col-md-6--><div class=\"col-md-6\"><input class=\"contact-input white-input\" required=\"\" name=\"contact_email\" placeholder=\"Adresse Mail*\" type=\"email\"> <input class=\"contact-input white-input\" required=\"\" name=\"contact_phone\" placeholder=\"Téléphone*\" type=\"text\"></div><!--end col-md-6--><!--begin col-md-6--><div class=\"col-md-12\"><textarea class=\"contact-commnent white-input\" rows=\"2\" cols=\"20\" name=\"contact_message\" placeholder=\"Votre Message...\"></textarea></div><!--end col-md-6--><!--begin col-md-12--><div class=\"col-md-12\"><input value=\"Envoyer\" id=\"submit-button\" class=\"contact-submit\" type=\"submit\"></div><!--end col-md-12--></form><!--end contact form --></div><!--end row--></div><!--end container--></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
