// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func imgOverlay() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"fun-facts-wrapper\"><!--begin image-overlay --><div class=\"image-overlay\"></div><!--end image-overlay --><!--begin container--><div class=\"container fun-facts-inside\"><!--begin row--><div class=\"row\"><!--begin fun-facts-box --><div class=\"fun-facts-box text-center wow fadeIn\" data-wow-delay=\"0.15s\"><i class=\"icon icon-design-pencil-rule-streamline\"></i><p class=\"fun-facts-title\"><span class=\"facts-numbers\">1050+</span><br>Projects Completed</p></div><!--end fun-facts-box --><!--begin fun-facts-box --><div class=\"fun-facts-box text-center wow fadeIn\" data-wow-delay=\"0.3s\"><i class=\"icon icon-streamline-umbrella-weather\"></i><p class=\"fun-facts-title\"><span class=\"facts-numbers\">217k</span><br>Happy Clients</p></div><!--end fun-facts-box --><!--begin fun-facts-box --><div class=\"fun-facts-box text-center wow fadeIn\" data-wow-delay=\"0.45s\"><i class=\"icon icon-crown-king-streamline\"></i><p class=\"fun-facts-title\"><span class=\"facts-numbers\">1210</span><br>Design Awards</p></div><!--end fun-facts-box --><!--begin fun-facts-box --><div class=\"fun-facts-box text-center wow fadeIn\" data-wow-delay=\"0.6s\"><i class=\"icon icon-cocktail-mojito-streamline\"></i><p class=\"fun-facts-title\"><span class=\"facts-numbers\">2137</span><br>Cups Of Coffee</p></div><!--end fun-facts-box --><!--begin fun-facts-box --><div class=\"fun-facts-box text-center wow fadeIn\" data-wow-delay=\"0.75s\"><i class=\"icon icon-speech-streamline-talk-user\"></i><p class=\"fun-facts-title\"><span class=\"facts-numbers\">24/7</span><br>Fast Support</p></div><!--end fun-facts-box --></div><!--end row--></div><!--end container--></div><!--end fun-facts -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
