// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/Alexis3386/goPortfolio/templates/project"

func portfolio() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"section-white portfolio-padding portfolio\" id=\"portfolio\"><!--begin container--><div class=\"container\"><!--begin row--><div class=\"row margin-bottom-50\"><!--begin col-md-12--><div class=\"col-md-12 text-center\"><h2 class=\"section-title\">Mes derniers projects</h2><div class=\"separator_wrapper\"><i class=\"icon icon-star-two blue\"></i></div><p class=\"section-subtitle\">There are many variations of passages of Lorem Ipsum available, but the majority<br>have suffered alteration, by injected humour, or new randomised words.</p></div><!--end col-md-12--></div><!--end row--><!--begin row--><div class=\"row\"><!--begin col-sm-4--><div class=\"col-sm-4 wow fadeIn\" data-wow-delay=\"0.15s\"><!--begin popup-gallery--><div id=\"project-1\" class=\"show-project\" data-target=\"project-panel-1\"><img src=\"http://placehold.it/800x550\" class=\"width-100\" alt=\"pic\"></div><div class=\"project-panel\" id=\"project-panel-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = project.Project1().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><!--end popup-gallery--></div><!--end col-sm-4--><!--begin col-sm-4--><div class=\"col-sm-4 wow fadeIn\" data-wow-delay=\"0.30s\"><!--begin popup-gallery--><div id=\"project-2\" class=\"show-project\" data-target=\"project-panel-2\"><img src=\"http://placehold.it/800x550\" class=\"width-100\" alt=\"pic\"></div><div class=\"project-panel\" id=\"project-panel-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = project.Project2().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><!--end popup-gallery--></div><!--end col-sm-4--><!--begin col-sm-4--><div class=\"col-sm-4 wow fadeIn\" data-wow-delay=\"0.45s\"><!--begin popup-gallery--><div class=\"\"><img src=\"http://placehold.it/800x550\" class=\"width-100\" alt=\"pic\"></div><!--end popup-gallery--></div><!--end col-sm-4--></div><!--end row--><!--begin row--><div class=\"row\"><!--begin col-sm-4--><div class=\"col-sm-4 wow fadeIn\" data-wow-delay=\"0.60s\"><!--begin popup-gallery--><div class=\"\"><img src=\"http://placehold.it/800x550\" class=\"width-100\" alt=\"pic\"></div><!--end popup-gallery--></div><!--end col-sm-4--><!--begin col-sm-4--><div class=\"col-sm-4 wow fadeIn\" data-wow-delay=\"0.75s\"><!--begin popup-gallery--><div class=\"\"><img src=\"http://placehold.it/800x550\" class=\"width-100\" alt=\"pic\"></div><!--end popup-gallery--></div><!--end col-sm-4--><!--begin col-sm-4--><div class=\"col-sm-4 wow fadeIn\" data-wow-delay=\"1s\"><!--begin popup-gallery--><div class=\"\"><img src=\"http://placehold.it/800x550\" class=\"width-100\" alt=\"pic\"></div><!--end popup-gallery--></div><!--end col-sm-4--></div><!--end row--></div><!--end container--></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
